### ISSUE TITLE
SteamGuard fail

### ISSUE THREAD

**Issue by SebRut** [twisterghost/jankbot#18]
Sometimes login fails with error 63. This is SteamGuard related and adding "authCode: STEAMGUARDCODE" in bot.logOn solves this issue.

**Comment by twisterghost** [comment]
Is this something that can be fixed in a pull request? Do you have a code snippet I could see?

Generally it works best to just have steam guard disabled on the bot account so that this won't be an issue. Sometimes it does get automatically turned back on, though. It is definitely something that could use a fix to make it easier to spin up a bot.

**Comment by SebRut** [comment]
Well, I manually added that line to logOn to get my bot running, and disabled Steamguard afterwards, but it took me some time to figure out what the problem is. I also read something about sentryHash. maybe this can be used to permanently makr an device/server. At least, there should be a message indicating what the problem is.

**Comment by twisterghost** [comment]
You're right for sure - Jankbot could use some descriptive warnings for known failures like this. There is a section in the [FAQ](https://github.com/twisterghost/jankbot#faq) about this issue, but the bot itself should catch this `logOn` error and print a better error with the solution steps.

I'll create a new issue for this and link to this.

**Comment by twisterghost** [comment]
Keeping this issue open for potential solutions to be found for the `steamguard` issue
