### ISSUE TITLE
modules' export.save not getting called

### ISSUE THREAD

**Issue by SebRut** [twisterghost/jankbot#22]
I've noticed on multiple modules, that sutff like quotes are not getting saved and that other stuff called in export.save is not getting called.

**Comment by twisterghost** [comment]
Is jankbot being shut down with a command or from an error?

**Comment by SebRut** [comment]
I tried both, exiting with "admin quit" and from console with CTRL+C.

Michael Barrett <notifications@github.com> schrieb am Do., 18. Juni 2015
00:15:

**Comment by SebRut** [comment]
Oh,  just noticed, the coin balance is getting saved, strange.

Sebastian Rutofski <sebastian.rutofski@gmail.com> schrieb am Do., 18. Juni
2015 07:04:

**Comment by twisterghost** [comment]
Most modules should be written to save whenever data is changed. Data managed through the `friends` module is automatically saved. Extraneous data to be saved though `exports.onExit()` will be called when the `admin quit` command is issued.

That said, I'll look into making Jankbot run the shutdown function (which runs all of the module `onExit` methods) when an interrupt is received or if there is a crash.

**Comment by twisterghost** [comment]
This should now be fixed in df98af1c84deede06b7f8999f0e269b1a6c58610. If Jankbot received a `SIGINT` or `SIGTERM`, it will now call the graceful shutdown function.

Also note that `exports.onExit` functions should be synchronous to ensure they execute fully. If you are saving data in these methods, I suggest the use of `fs.writeFileSync`.
